---
title: Kubusboom
hero_image: images/banner.png
description: Leer om objecten van grootte te veranderen in Blender door een simpele
  boom van kubussen te maken
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2017-01-01
steps:
- title: Inleiding
  completion: engaged
- title: Objecten selecteren
- title: Objecten toevoegen
- title: Maak een boomstam
- title: Voeg takken en bladeren toe
- title: Renderen
  completion: internal
- title: 'Uitdaging: dennenboom'
