---
title: क्यूब्स का पेड़
hero_image: images/banner.png
description: क्यूब्स का एक साधारण पेड़ बनाकर यह सीखें कि Blender में वस्तुओं के आकार को कैसे बदला जाता है।
theme: yellow #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: Selecting objects
  - 
    title: Adding objects
  - 
    title: Create a tree trunk
  - 
    title: Add branches and leaves
  - 
    title: Render
  - 
    title: "Challenge: pine tree"
