---
title: Tree of cubes
hero_image: images/banner.png
description: Learn how to resize objects in Blender by creating a simple tree of cubes
theme: màu vàng
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, thiết kế-1, lập trình-0, Phys-comp-0, sản xuất-0, cộng đồng-0
interests: weather, art
technologies: blender
site_areas: dự án
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Selecting objects
  - 
    title: Adding objects
  - 
    title: Create a tree trunk
  - 
    title: Add branches and leaves
  - 
    title: Render
  - 
    title: "Challenge: pine tree"
