---
title: Copac din cuburi
hero_image: images/banner.png
description: Învață cum să redimensionezi obiecte în Blender creând un copac simplu format din cuburi
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Selecting objects
  - 
    title: Adding objects
    completion:
      - engaged
  - 
    title: Create a tree trunk
  - 
    title: Add branches and leaves
  - 
    title: Render
    completion:
      - internal
  - 
    title: 'Challenge: pine tree'
