---
title: Tree of cubes
hero_image: imagens/banner.png
description: Learn how to resize objects in Blender by creating a simple tree of cubes
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: liquidificador
site_areas: projects
hardware: ''
software: liquidificador
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introdução
  - 
    title: O que você vai precisar
  - 
    title: Selecting objects
  - 
    title: Adding objects
  - 
    title: Create a tree trunk
  - 
    title: Add branches and leaves
  - 
    title: Render
  - 
    title: "Challenge: pine tree"
