---
title: Tree of cubes
hero_image: images/banner.png
description: Learn how to resize objects in Blender by creating a simple tree of cubes
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1，design-1，programming-0，phys-comp-0，manufacture-0，community-0
interests: weather, art
technologies: 攪拌器
site_areas: projects
hardware: ''
software: 攪拌器
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 介紹
  - 
    title: 你會需要
  - 
    title: Selecting objects
  - 
    title: Adding objects
  - 
    title: Create a tree trunk
  - 
    title: Add branches and leaves
  - 
    title: Render
  - 
    title: "Challenge: pine tree"
