---
title: Tree of cubes
hero_image: images / banner.png
description: Learn how to resize objects in Blender by creating a simple tree of cubes
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: blender
site_areas: projekty
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Co będzie potrzebne
  - 
    title: Selecting objects
  - 
    title: Adding objects
  - 
    title: Create a tree trunk
  - 
    title: Add branches and leaves
  - 
    title: Render
  - 
    title: "Challenge: pine tree"
